# Generated by Django 3.1.5 on 2021-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210119_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default=1, verbose_name='Local do evento'),
            preserve_default=False,
        ),
    ]
